# Generated by Django 4.1 on 2024-12-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
